[phases.setup]
nixPkgs = ["nodejs", "bun"]
nixpkgsArchive = "0e0a18f576aa37127085f19e87dd19263f7eba9a"

[phases.install]
cmds = ["bun install"]

[phases.build]
cmds = [
  "bun run build --filter=@optioo/web",
  "mkdir -p apps/api/frontend/dist",
  "cp -r apps/web/dist/* apps/api/frontend/dist/",
  "cd apps/api && bun build index.ts --compile --outfile=prod-server",
  "mv apps/api/prod-server /app/prod-server",
  "chmod +x /app/prod-server"
]

[phases.postBuild]
cmds = [
  "mkdir -p /app/apps/api/frontend/dist",
  "cp -r /app/apps/web/dist/* /app/apps/api/frontend/dist/ || true",
  "ls -la /app/apps/api/frontend/dist || true"
]

[start]
cmd = "/app/prod-server"

[variables]
NODE_ENV = "production"
PORT = "8000"
