# Nixpacks configuration for Coolify deployment
[phases.setup]
nixPkgs = ["nodejs", "bun"]
nixpkgsArchive = '0e0a18f576aa37127085f19e87dd19263f7eba9a'


[phases.install]
cmds = ["bun install"]

[phases.build]
cmds = [
  "bun run build --filter=@optioo/web",
  "mkdir -p apps/api/frontend/dist",
  "cp -r apps/web/dist/* apps/api/frontend/dist/",
  "cd apps/api && bun build index.ts --compile --outfile=prod-server && mv prod-server /usr/local/bin/optioo-server && chmod +x /usr/local/bin/optioo-server && ls -la /usr/local/bin/optioo-server"
]

[start]
cmd = "bun optioo-server"

[variables]
NODE_ENV = "production"
PORT = "8000"
