[phases.setup]
nixPkgs = ["nodejs", "bun"]
nixpkgsArchive = "0e0a18f576aa37127085f19e87dd19263f7eba9a"

[phases.install]
cmds = ["bun install"]

[phases.build]
cmds = [
  "bun run build --filter=@your-org/web",
  "mkdir -p /app/_static",
  "cp -r apps/web/dist/* /app/_static/",
  "cd apps/api && bun build index.ts --compile --outfile=prod-server",
  "mv apps/api/prod-server /app/prod-server",
  "chmod +x /app/prod-server",
  "ls -la /app/_static || true",
  "ls -la /app/prod-server || true"
]

[start]
cmd = "/app/prod-server"

[variables]
NODE_ENV = "production"
PORT = "8000"
